cake-contrib/Cake.BuildSystems.Module

ReleaseNotes.md
build.cake
src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.MyGet.Module/MyGetBuildLog.cs
src/Cake.TFBuild.Module/Cake.TFBuild.Module.csproj
src/Cake.TFBuild.Module/TFBuildLog.cs
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TeamCity.Module/TeamCityLog.cs
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj

Update Cake to 0.22.2

---

src/Cake.TeamCity.Module/TeamCityLog.cs

Escape special characters for TeamCity service messages

---

build.cake

Use cake-contrib icon for NuGet package

---

src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.TFBuild.Module/Cake.TFBuild.Module.csproj
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj

Make Cake references private

---

src/Cake.MyGet.Module/MyGetModule.cs
src/Cake.TeamCity.Module/TeamCityModule.cs
src/Cake.TravisCI.Module/TravisCIModule.cs

(GH-36) declared the CakeModules public

---

src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj

tfs, azure devops, azure devops server, myget, teamcity, travisci
fixes #34

(GH-34) added tags

---

.github/workflows/build.yml

(GH-33) added a workflow for GitHub Actions

---

.github/workflows/codeql-analysis.yml

(GH-31) added the CodeQL workflow

---

.github/dependabot.yml
.github/workflows/dependabot-cake.yml

and the dependabot-cake workflow
fixes #32

(GH-32) added a dependabot configuration

---

src/Cake.AzurePipelines.Module/Cake.AzurePipelines.Module.csproj
src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj

(GH-45) Bumped Cake to 1.0.0

---

src/Cake.AzurePipelines.Module/Cake.AzurePipelines.Module.csproj
src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj
src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj

(GH-52) Remove net461 target, leaving only netstandard2.0

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

to current best practices
fixes #59

(GH-59) updated gh actions

---

src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj

(GH-57) updated tags

---

GitReleaseManager.yaml

(GH-58) updated GRM config

---

src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj

(GH-64) updated CCG

---

src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj

this will also update the logo and fix #69

(GH-69) updated CakeContrib.Guidelines

---

src/Cake.AzurePipelines.Module/AzurePipelinesEngine.cs
src/Cake.AzurePipelines.Module/AzurePipelinesReportPrinter.cs
src/Cake.AzurePipelines.Module/Cake.AzurePipelines.Module.csproj
src/Cake.AzurePipelines.Module/Extensions.cs
src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj
src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.Module.Shared/CakeEngineBase.cs
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.MyGet.Module/MyGetEngine.cs
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TeamCity.Module/TeamCityEngine.cs
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj
src/Cake.TravisCI.Module/TravisCIEngine.cs
src/Directory.Build.props

(#94) bumped Cake to 2.0.0-rc0001

---

recipe.cake

for https://github.com/cake-contrib/Cake.Recipe/issues/854
closes #98

(#98) implemented workaround

---

src/Cake.TeamCity.Module/TeamCityEngine.cs

Using the new events, send TeamCity progress and block messages for setup start/end
Fixes: #49

Update Task Start/Stop block messages for TeamCityEngine

---

src/Cake.AzurePipelines.Module/Cake.AzurePipelines.Module.csproj
src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj
src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj

and CakeContrib.Guidelines to 1.3.0
fixes #105

(#105) bumped Cake to 2.0.0

---

src/Cake.AzurePipelines.Module/AzurePipelinesLog.cs

Use of IConsole in AzurePipelineLog to bypass ANSI formating

---

src/Cake.AzurePipelines.Module/Cake.AzurePipelines.Module.csproj
src/Cake.BuildSystems.Module/Cake.BuildSystems.Module.csproj
src/Cake.GitHubActions.Module/Cake.GitHubActions.Module.csproj
src/Cake.Module.Shared/Cake.Module.Shared.csproj
src/Cake.Module.Shared/CakeEngineBase.cs
src/Cake.Module.Shared/CakeReportPrinterBase.cs
src/Cake.MyGet.Module/Cake.MyGet.Module.csproj
src/Cake.TeamCity.Module/Cake.TeamCity.Module.csproj
src/Cake.TravisCI.Module/Cake.TravisCI.Module.csproj

I've tested that these changes allow [our build](https://github.com/dnnsoftware/Dnn.Platform/tree/develop/Build) to work successfully when targeting Cake 3. Thanks!

Update dependency to Cake 3

---

recipe.cake

(GH-245) bumped GRM to 0.18.0
